[package]
authors     = ["Xavier Lau <xavier@inv.cafe>"]
description = "primitives-b"
edition     = "2021"
homepage    = "https://subalfred.hack.ink"
license     = "GPL-3.0"
name        = "primitive-b"
readme      = "README.md"
repository  = "https://github.com/hack-ink/subalfred"
version     = "0.0.0"

[features]
default = ["std"]
std     = []
