[package]
authors     = ["Xavier Lau <xavier@inv.cafe>"]
description = "Subalfred CMD example - check"
edition     = "2021"
homepage    = "https://hack.ink/subalfred"
license     = "GPL-3.0"
name        = "sce-check"
readme      = "README.md"
repository  = "https://github.com/hack-ink/subalfred"
version     = "0.0.0"

[dependencies]
se-util = { version = "0.0.0", path = "../../util" }
