[package]
authors     = ["Xavier Lau <xavier@inv.cafe>"]
description = "subalfred-state-example"
edition     = "2021"
homepage    = "https://subalfred.hack.ink"
license     = "GPL-3.0"
name        = "subalfred-state-example"
readme      = "README.md"
repository  = "https://github.com/hack-ink/subalfred"
version     = "0.0.0"

[dependencies]
parity-scale-codec     = { version = "3.2" }
sp-keyring             = { version = "6.0" }
subalfred-example-util = { version = "0.0.0", path = "../../util" }
subxt                  = { version = "0.24" }
tokio                  = { version = "1.21", features = ["rt-multi-thread"] }
