name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.system }} package
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [ubuntu-latest, macos-latest]
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v3
      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked
      - name: Compress
        run: |
          mv target/release/subalfred .
          tar cf subalfred-${{ matrix.system }}.tar.zst subalfred -I pzstd
      - name: Collect artifact
        run: |
          mkdir -p artifacts
          mv subalfred-${{ matrix.system }}.tar.zst artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: artifacts
          path: artifacts

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts
      - name: Hash
        run: |
          cd artifacts
          sha256sum * | tee ../SHA256
          md5sum * | tee ../MD5
          mv ../SHA256 artifacts
          mv ../MD5 artifacts
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          discussion_category_name: Announcements
          generate_release_notes: true
          files: artifacts/*
