name: Staging
on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }} package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v3
      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target ${{ matrix.target }}
      - name: Compress
        run: |
          mv target/${{ matrix.target }}/release/subalfred .
          zstd --ultra -22 -o subalfred-${{ matrix.target }}.zst subalfred
      - name: Collect artifact
        run: |
          mkdir -p artifacts
          mv subalfred-${{ matrix.target }}.zst artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: artifacts
          path: artifacts

  staging:
    name: Staging
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts
      - name: Hash
        run: |
          cd artifacts
          sha256sum * | tee ../SHA256
          md5sum * | tee ../MD5
          mv ../SHA256 .
          mv ../MD5 .

  clean-artifacts:
    name: Clean artifacts
    if: always()
    needs: [staging]
    steps:
      - name: Clean artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: artifacts
    runs-on: ubuntu-latest
