name: Staging
on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }} package
    runs-on: ${{ matrix.env.os }}
    strategy:
      matrix:
        target:
          [x86_64-unknown-linux-gnu, aarch64-apple-darwin, x86_64-apple-darwin]
        env:
          [
            { os: ubuntu-latest, compressor: tar },
            { os: macos-latest, compressor: gtar },
          ]
        exclude:
          - target: aarch64-apple-darwin
            env: { os: ubuntu-latest }
          - target: x86_64-apple-darwin
            env: { os: ubuntu-latest }
          - target: x86_64-unknown-linux-gnu
            env: { os: macos-latest }
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v3
      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target ${{ matrix.target }}
      - name: Compress
        run: |
          mv target/${{ matrix.target }}/release/subalfred .
          ${{ matrix.env.compressor }} cf subalfred-${{ matrix.target }}.tar.zst subalfred -I pzstd
      - name: Collect artifact
        run: |
          mkdir -p artifacts
          mv subalfred-${{ matrix.target }}.tar.zst artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: artifacts
          path: artifacts

  staging:
    name: Staging
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts
      - name: Hash
        run: |
          cd artifacts
          sha256sum * | tee ../SHA256
          md5sum * | tee ../MD5
          mv ../SHA256 artifacts
          mv ../MD5 artifacts

  clean-artifacts:
    name: Clean artifacts
    if: always()
    needs: [staging]
    steps:
      - name: Clean artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: artifacts
    runs-on: ubuntu-latest
